language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
before_install:
  - pip install -U pip
  - pip install --upgrade pip setuptools wheel
install: 
  - "pip install --only-binary=scipy -r requirements.txt" 
# command to run tests
script: python test_seam_carver.py
